version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  app:
    image: shiravand/mongodb-demo
    container_name: app
    depends_on:
      - mongodb
    ports:
      - 8080:8080
